export type GameRuleErrorCode =
  | 'GAME_ALREADY_COMPLETED'
  | 'INVALID_TEAM_COUNT'
  | 'INVALID_TEAM'
  | 'DUPLICATE_TEAM_ID'
  | 'INVALID_CATEGORY_COUNT'
  | 'DUPLICATE_CATEGORY'
  | 'LEVEL_ALREADY_STARTED'
  | 'LEVEL_ORDER_REQUIRED'
  | 'ACTIVE_TURN_EXISTS'
  | 'NO_ACTIVE_TURN'
  | 'UNEXPECTED_PRIMARY_TEAM'
  | 'CATEGORY_NOT_IN_ROUND'
  | 'CATEGORY_ALREADY_CONSUMED'
  | 'CATEGORY_ALREADY_CONFIRMED'
  | 'CHALLENGE_MISMATCH'
  | 'CHALLENGE_ALREADY_PLAYED'
  | 'CHALLENGE_REQUIRED'
  | 'INVALID_PRIMARY_RESULT'
  | 'PRIMARY_RESULT_REQUIRED'
  | 'PRIMARY_ALREADY_CLASSIFIED'
  | 'STEAL_NOT_ELIGIBLE'
  | 'STEAL_ALREADY_STARTED'
  | 'STEAL_REQUIRED'
  | 'STEAL_ALREADY_CLASSIFIED'
  | 'LIFELINE_NOT_AVAILABLE'
  | 'LIFELINE_AFTER_CLASSIFICATION'
  | 'LIFELINE_DURING_STEAL_DISABLED'
  | 'PAID_LIFELINE_CONFIRMATION_REQUIRED'
  | 'SCORE_REQUIRED'
  | 'SCORE_ALREADY_APPLIED'
  | 'SCORE_OVERRIDE_DISABLED'
  | 'INVALID_SCORE_OVERRIDE'
  | 'TURN_NOT_READY'
  | 'NO_AVAILABLE_CATEGORY'
  | 'INVALID_RANDOM_VALUE';

export class GameRuleError extends Error {
  readonly code: GameRuleErrorCode;

  constructor(code: GameRuleErrorCode, message: string) {
    super(message);
    this.name = 'GameRuleError';
    this.code = code;
  }
}
