import type { GamePhase } from '../enums';

export const LEGAL_PHASE_TRANSITIONS: Readonly<Record<GamePhase, readonly GamePhase[]>> = {
  GAME_SETUP: ['ROUND_BUILDING', 'RECOVERY'],
  ROUND_BUILDING: ['ROUND_VALIDATION', 'RECOVERY'],
  ROUND_VALIDATION: ['ROUND_BUILDING', 'LEVEL_INTRO', 'RECOVERY'],
  LEVEL_INTRO: ['TRIVIA_RESULT_ENTRY', 'GAME_SUMMARY', 'RECOVERY'],
  TRIVIA_RESULT_ENTRY: ['TURN_ORDER_CONFIRMATION', 'GAME_SUMMARY', 'RECOVERY'],
  TURN_ORDER_CONFIRMATION: ['CATEGORY_ASSIGNMENT', 'GAME_SUMMARY', 'RECOVERY'],
  CATEGORY_ASSIGNMENT: ['CHALLENGE_SELECTION', 'GAME_SUMMARY', 'RECOVERY'],
  CHALLENGE_SELECTION: ['CHALLENGE_PREVIEW', 'GAME_SUMMARY', 'RECOVERY'],
  CHALLENGE_PREVIEW: ['CHALLENGE_SELECTION', 'VIDEO_LOADING', 'GAME_SUMMARY', 'RECOVERY'],
  VIDEO_LOADING: ['VIDEO_READY', 'GAME_SUMMARY', 'RECOVERY'],
  VIDEO_READY: ['VIDEO_PLAYING', 'GAME_SUMMARY', 'RECOVERY'],
  VIDEO_PLAYING: ['PRIMARY_ANSWERING', 'GAME_SUMMARY', 'RECOVERY'],
  PRIMARY_ANSWERING: ['PRIMARY_RESULT_REVIEW', 'GAME_SUMMARY', 'RECOVERY'],
  PRIMARY_RESULT_REVIEW: ['STEAL_OFFER', 'CHALLENGE_VERIFICATION', 'GAME_SUMMARY', 'RECOVERY'],
  STEAL_OFFER: ['STEAL_ANSWERING', 'CHALLENGE_VERIFICATION', 'GAME_SUMMARY', 'RECOVERY'],
  STEAL_ANSWERING: ['STEAL_RESULT_REVIEW', 'GAME_SUMMARY', 'RECOVERY'],
  STEAL_RESULT_REVIEW: ['CHALLENGE_VERIFICATION', 'GAME_SUMMARY', 'RECOVERY'],
  CHALLENGE_VERIFICATION: ['FINAL_SCORE_REVIEW', 'GAME_SUMMARY', 'RECOVERY'],
  FINAL_SCORE_REVIEW: ['TURN_SUMMARY', 'GAME_SUMMARY', 'RECOVERY'],
  TURN_SUMMARY: ['CATEGORY_ASSIGNMENT', 'LEVEL_SUMMARY', 'GAME_SUMMARY', 'RECOVERY'],
  LEVEL_SUMMARY: ['LEVEL_INTRO', 'GAME_SUMMARY', 'RECOVERY'],
  GAME_SUMMARY: [],
  RECOVERY: [
    'GAME_SETUP',
    'ROUND_BUILDING',
    'ROUND_VALIDATION',
    'LEVEL_INTRO',
    'TRIVIA_RESULT_ENTRY',
    'TURN_ORDER_CONFIRMATION',
    'CATEGORY_ASSIGNMENT',
    'CHALLENGE_SELECTION',
    'CHALLENGE_PREVIEW',
    'VIDEO_READY',
    'PRIMARY_ANSWERING',
    'PRIMARY_RESULT_REVIEW',
    'STEAL_OFFER',
    'STEAL_ANSWERING',
    'STEAL_RESULT_REVIEW',
    'CHALLENGE_VERIFICATION',
    'FINAL_SCORE_REVIEW',
    'TURN_SUMMARY',
    'LEVEL_SUMMARY',
    'GAME_SUMMARY',
  ],
  ERROR: ['GAME_SUMMARY', 'RECOVERY'],
};

export function isLegalPhaseTransition(from: GamePhase, to: GamePhase): boolean {
  return LEGAL_PHASE_TRANSITIONS[from].includes(to);
}

export function canRevealExpectedLyrics(phase: GamePhase): boolean {
  return [
    'CHALLENGE_VERIFICATION',
    'FINAL_SCORE_REVIEW',
    'TURN_SUMMARY',
    'LEVEL_SUMMARY',
    'GAME_SUMMARY',
  ].includes(phase);
}
